// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NexusProcure.Infrastructure.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NexusProcure.Infrastructure.Migrations
{
    [DbContext(typeof(NexusProcureDbContext))]
    [Migration("20251123061000_AddedDescriptionRoleDepartment")]
    partial class AddedDescriptionRoleDepartment
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NexusProcure.Core.Entities.Approval", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ApprovedById")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ApprovedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RequisitionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedById");

                    b.HasIndex("RequisitionId");

                    b.ToTable("Approvals");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.ApprovalLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("LevelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("MaxAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MinAmount")
                        .HasColumnType("numeric");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("ApprovalLevels");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.AssetAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AssignedToId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConditionOnReturn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("InventoryItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ReturnedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToId");

                    b.HasIndex("InventoryItemId");

                    b.ToTable("AssetAssignments");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PerformedById")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PerformedById");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("HeadId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("HeadId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.InventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssetTag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("InventoryItems");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Description = "View all users",
                            Group = "User",
                            Key = "VIEW_USERS"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Description = "Add new users",
                            Group = "User",
                            Key = "CREATE_USER"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Description = "Edit existing users",
                            Group = "User",
                            Key = "EDIT_USER"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            Description = "Delete users",
                            Group = "User",
                            Key = "DELETE_USER"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            Description = "View roles",
                            Group = "Role",
                            Key = "VIEW_ROLES"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            Description = "Create new roles",
                            Group = "Role",
                            Key = "CREATE_ROLE"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            Description = "Edit roles",
                            Group = "Role",
                            Key = "EDIT_ROLE"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            Description = "Delete roles",
                            Group = "Role",
                            Key = "DELETE_ROLE"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000005"),
                            Description = "Assign or revoke permissions for roles",
                            Group = "Role",
                            Key = "MANAGE_ROLE_PERMISSIONS"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            Description = "View departments",
                            Group = "Department",
                            Key = "VIEW_DEPARTMENTS"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            Description = "Add new departments",
                            Group = "Department",
                            Key = "CREATE_DEPARTMENT"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            Description = "Edit departments",
                            Group = "Department",
                            Key = "EDIT_DEPARTMENT"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000004"),
                            Description = "Delete departments",
                            Group = "Department",
                            Key = "DELETE_DEPARTMENT"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000001"),
                            Description = "View vendor list",
                            Group = "Vendor",
                            Key = "VIEW_VENDORS"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000002"),
                            Description = "Add new vendor",
                            Group = "Vendor",
                            Key = "CREATE_VENDOR"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000003"),
                            Description = "Edit vendor details",
                            Group = "Vendor",
                            Key = "EDIT_VENDOR"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000004"),
                            Description = "Delete vendor",
                            Group = "Vendor",
                            Key = "DELETE_VENDOR"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000001"),
                            Description = "Create purchase requisition",
                            Group = "Procurement",
                            Key = "CREATE_REQUISITION"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000002"),
                            Description = "Approve requisition",
                            Group = "Procurement",
                            Key = "APPROVE_REQUISITION"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000003"),
                            Description = "Create purchase order",
                            Group = "Procurement",
                            Key = "CREATE_PURCHASE_ORDER"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000004"),
                            Description = "View purchase order details",
                            Group = "Procurement",
                            Key = "VIEW_PURCHASE_ORDER"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000001"),
                            Description = "View inventory list",
                            Group = "Inventory",
                            Key = "VIEW_INVENTORY"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000002"),
                            Description = "Add new inventory items",
                            Group = "Inventory",
                            Key = "ADD_INVENTORY_ITEM"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000003"),
                            Description = "Update inventory items",
                            Group = "Inventory",
                            Key = "UPDATE_INVENTORY_ITEM"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000004"),
                            Description = "Delete inventory items",
                            Group = "Inventory",
                            Key = "DELETE_INVENTORY_ITEM"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000005"),
                            Description = "Assign asset to employee",
                            Group = "Inventory",
                            Key = "ASSIGN_ASSET"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000006"),
                            Description = "Return assigned asset",
                            Group = "Inventory",
                            Key = "RETURN_ASSET"
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000001"),
                            Description = "View reports",
                            Group = "Reporting",
                            Key = "VIEW_REPORTS"
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000002"),
                            Description = "Export reports to PDF/Excel",
                            Group = "Reporting",
                            Key = "EXPORT_REPORTS"
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000001"),
                            Description = "Change global settings",
                            Group = "System",
                            Key = "MANAGE_SYSTEM_SETTINGS"
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000002"),
                            Description = "View audit logs",
                            Group = "System",
                            Key = "VIEW_AUDIT_LOGS"
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000003"),
                            Description = "Configure approval workflow",
                            Group = "System",
                            Key = "MANAGE_APPROVAL_WORKFLOW"
                        });
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.PurchaseOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RequisitionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RequisitionId");

                    b.HasIndex("VendorId");

                    b.ToTable("PurchaseOrders");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.PurchaseOrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PurchaseOrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseOrderId");

                    b.ToTable("PurchaseOrderItems");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.Requisition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequestedById")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RequestedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("RequestedById");

                    b.ToTable("Requisitions");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.RequisitionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("EstimatedCost")
                        .HasColumnType("numeric");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("RequisitionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RequisitionId");

                    b.ToTable("RequisitionItems");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c76abcb8-63b5-4e14-8428-3a9a9b7ad001"),
                            Description = "",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("d27f6b43-9f64-4b13-a289-fd7744f2f102"),
                            Description = "",
                            Name = "CEO"
                        },
                        new
                        {
                            Id = new Guid("b38b2e23-6a7e-4c6d-9d5e-437a78c7b203"),
                            Description = "",
                            Name = "ProcurementOfficer"
                        });
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("c76abcb8-63b5-4e14-8428-3a9a9b7ad001"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("c76abcb8-63b5-4e14-8428-3a9a9b7ad001"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            RoleId = new Guid("c76abcb8-63b5-4e14-8428-3a9a9b7ad001"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            RoleId = new Guid("c76abcb8-63b5-4e14-8428-3a9a9b7ad001"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            RoleId = new Guid("c76abcb8-63b5-4e14-8428-3a9a9b7ad001"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("c76abcb8-63b5-4e14-8428-3a9a9b7ad001"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            RoleId = new Guid("c76abcb8-63b5-4e14-8428-3a9a9b7ad001"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            RoleId = new Guid("c76abcb8-63b5-4e14-8428-3a9a9b7ad001"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            RoleId = new Guid("c76abcb8-63b5-4e14-8428-3a9a9b7ad001"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            RoleId = new Guid("c76abcb8-63b5-4e14-8428-3a9a9b7ad001"),
                            PermissionId = new Guid("30000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("c76abcb8-63b5-4e14-8428-3a9a9b7ad001"),
                            PermissionId = new Guid("30000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            RoleId = new Guid("c76abcb8-63b5-4e14-8428-3a9a9b7ad001"),
                            PermissionId = new Guid("30000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            RoleId = new Guid("c76abcb8-63b5-4e14-8428-3a9a9b7ad001"),
                            PermissionId = new Guid("30000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            RoleId = new Guid("c76abcb8-63b5-4e14-8428-3a9a9b7ad001"),
                            PermissionId = new Guid("40000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("c76abcb8-63b5-4e14-8428-3a9a9b7ad001"),
                            PermissionId = new Guid("40000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            RoleId = new Guid("c76abcb8-63b5-4e14-8428-3a9a9b7ad001"),
                            PermissionId = new Guid("40000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            RoleId = new Guid("c76abcb8-63b5-4e14-8428-3a9a9b7ad001"),
                            PermissionId = new Guid("40000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            RoleId = new Guid("c76abcb8-63b5-4e14-8428-3a9a9b7ad001"),
                            PermissionId = new Guid("50000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("c76abcb8-63b5-4e14-8428-3a9a9b7ad001"),
                            PermissionId = new Guid("50000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            RoleId = new Guid("c76abcb8-63b5-4e14-8428-3a9a9b7ad001"),
                            PermissionId = new Guid("50000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            RoleId = new Guid("c76abcb8-63b5-4e14-8428-3a9a9b7ad001"),
                            PermissionId = new Guid("50000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            RoleId = new Guid("c76abcb8-63b5-4e14-8428-3a9a9b7ad001"),
                            PermissionId = new Guid("60000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("c76abcb8-63b5-4e14-8428-3a9a9b7ad001"),
                            PermissionId = new Guid("60000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            RoleId = new Guid("c76abcb8-63b5-4e14-8428-3a9a9b7ad001"),
                            PermissionId = new Guid("60000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            RoleId = new Guid("c76abcb8-63b5-4e14-8428-3a9a9b7ad001"),
                            PermissionId = new Guid("60000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            RoleId = new Guid("c76abcb8-63b5-4e14-8428-3a9a9b7ad001"),
                            PermissionId = new Guid("60000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            RoleId = new Guid("c76abcb8-63b5-4e14-8428-3a9a9b7ad001"),
                            PermissionId = new Guid("60000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            RoleId = new Guid("c76abcb8-63b5-4e14-8428-3a9a9b7ad001"),
                            PermissionId = new Guid("70000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("c76abcb8-63b5-4e14-8428-3a9a9b7ad001"),
                            PermissionId = new Guid("70000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            RoleId = new Guid("c76abcb8-63b5-4e14-8428-3a9a9b7ad001"),
                            PermissionId = new Guid("80000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("c76abcb8-63b5-4e14-8428-3a9a9b7ad001"),
                            PermissionId = new Guid("80000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            RoleId = new Guid("c76abcb8-63b5-4e14-8428-3a9a9b7ad001"),
                            PermissionId = new Guid("80000000-0000-0000-0000-000000000003")
                        });
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PasswordResetToken")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("PasswordResetTokenExpiration")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("PasswordResetTokenUsed")
                        .HasColumnType("boolean");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a87f3d2b-0f0d-4b4e-9d2a-4e09d68f4104"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@nexusprocure.com",
                            FullName = "",
                            IsActive = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEHsHTY55ymmyC5FW7c6RpK2s/HWufLsNpUswO1iSjCFPadhi/WF+HZo86Twk4Rl4NQ==",
                            PasswordResetTokenExpiration = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordResetTokenUsed = false,
                            RoleId = new Guid("c76abcb8-63b5-4e14-8428-3a9a9b7ad001"),
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.Vendor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactPerson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VendorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Vendors");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.Approval", b =>
                {
                    b.HasOne("NexusProcure.Core.Entities.User", "ApprovedBy")
                        .WithMany()
                        .HasForeignKey("ApprovedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexusProcure.Core.Entities.Requisition", "Requisition")
                        .WithMany("Approvals")
                        .HasForeignKey("RequisitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovedBy");

                    b.Navigation("Requisition");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.ApprovalLevel", b =>
                {
                    b.HasOne("NexusProcure.Core.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.AssetAssignment", b =>
                {
                    b.HasOne("NexusProcure.Core.Entities.User", "AssignedTo")
                        .WithMany("AssetAssignments")
                        .HasForeignKey("AssignedToId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexusProcure.Core.Entities.InventoryItem", "InventoryItem")
                        .WithMany("AssetAssignments")
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedTo");

                    b.Navigation("InventoryItem");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.AuditLog", b =>
                {
                    b.HasOne("NexusProcure.Core.Entities.User", "PerformedBy")
                        .WithMany()
                        .HasForeignKey("PerformedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerformedBy");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.Department", b =>
                {
                    b.HasOne("NexusProcure.Core.Entities.User", "Head")
                        .WithMany()
                        .HasForeignKey("HeadId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Head");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.PurchaseOrder", b =>
                {
                    b.HasOne("NexusProcure.Core.Entities.Requisition", "Requisition")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("RequisitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexusProcure.Core.Entities.Vendor", "Vendor")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Requisition");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.PurchaseOrderItem", b =>
                {
                    b.HasOne("NexusProcure.Core.Entities.PurchaseOrder", "PurchaseOrder")
                        .WithMany("Items")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.Requisition", b =>
                {
                    b.HasOne("NexusProcure.Core.Entities.Department", null)
                        .WithMany("Requisitions")
                        .HasForeignKey("DepartmentId");

                    b.HasOne("NexusProcure.Core.Entities.User", "RequestedBy")
                        .WithMany("Requisitions")
                        .HasForeignKey("RequestedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RequestedBy");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.RequisitionItem", b =>
                {
                    b.HasOne("NexusProcure.Core.Entities.Requisition", "Requisition")
                        .WithMany("Items")
                        .HasForeignKey("RequisitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Requisition");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.RolePermission", b =>
                {
                    b.HasOne("NexusProcure.Core.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexusProcure.Core.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.User", b =>
                {
                    b.HasOne("NexusProcure.Core.Entities.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId");

                    b.HasOne("NexusProcure.Core.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.Department", b =>
                {
                    b.Navigation("Requisitions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.InventoryItem", b =>
                {
                    b.Navigation("AssetAssignments");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.PurchaseOrder", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.Requisition", b =>
                {
                    b.Navigation("Approvals");

                    b.Navigation("Items");

                    b.Navigation("PurchaseOrders");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.User", b =>
                {
                    b.Navigation("AssetAssignments");

                    b.Navigation("Requisitions");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.Vendor", b =>
                {
                    b.Navigation("PurchaseOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
