// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NexusProcure.Infrastructure.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NexusProcure.Infrastructure.Migrations
{
    [DbContext(typeof(NexusProcureDbContext))]
    [Migration("20260404052329_UpdateGoodsReceipt")]
    partial class UpdateGoodsReceipt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("purchase_order_number_seq");

            modelBuilder.HasSequence("requisition_number_seq");

            modelBuilder.HasSequence("rfq_number_seq");

            modelBuilder.Entity("NexusProcure.Application.Interfaces.ApprovalDelegation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("FromUserId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ToUserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("ApprovalDelegations");
                });

            modelBuilder.Entity("NexusProcure.Core.DTOs.DashboardStatsDto", b =>
                {
                    b.Property<int>("ActivePurchaseOrders")
                        .HasColumnType("integer")
                        .HasColumnName("active_orders");

                    b.Property<int>("PendingRequisitionApprovals")
                        .HasColumnType("integer")
                        .HasColumnName("pending_requisition_approvals");

                    b.Property<int>("TotalDepartments")
                        .HasColumnType("integer")
                        .HasColumnName("total_departments");

                    b.Property<int>("TotalPurchaseOrders")
                        .HasColumnType("integer")
                        .HasColumnName("total_purchase_orders");

                    b.Property<int>("TotalQuotations")
                        .HasColumnType("integer")
                        .HasColumnName("total_quotations");

                    b.Property<int>("TotalRequisitions")
                        .HasColumnType("integer")
                        .HasColumnName("total_requisitions");

                    b.Property<int>("TotalRoles")
                        .HasColumnType("integer")
                        .HasColumnName("total_roles");

                    b.Property<int>("TotalUsers")
                        .HasColumnType("integer")
                        .HasColumnName("total_users");

                    b.Property<int>("TotalVendors")
                        .HasColumnType("integer")
                        .HasColumnName("total_vendors");

                    b.ToTable("DashboardStatsDto");
                });

            modelBuilder.Entity("NexusProcure.Core.DTOs.DeliveryDto", b =>
                {
                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("delivery_date");

                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("PoNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("po_number");

                    b.Property<int>("TotalItems")
                        .HasColumnType("integer")
                        .HasColumnName("total_items");

                    b.Property<string>("VendorName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("vendor_name");

                    b.ToTable("DeliveryDto");
                });

            modelBuilder.Entity("NexusProcure.Core.DTOs.RecentPurchaseOrderDto", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("PoNumber")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("po_number");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric")
                        .HasColumnName("total_amount");

                    b.Property<int>("TotalItems")
                        .HasColumnType("integer")
                        .HasColumnName("total_items");

                    b.Property<string>("VendorName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("vendor_name");

                    b.ToTable("RecentPurchaseOrderDto");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.Approval", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActionedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ApprovedById")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Comments")
                        .HasColumnType("text");

                    b.Property<bool>("Escalated")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("EscalatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ReferenceId")
                        .HasColumnType("uuid");

                    b.Property<int>("ReferenceType")
                        .HasColumnType("integer");

                    b.Property<Guid?>("RequisitionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ApprovedById");

                    b.HasIndex("RequisitionId");

                    b.HasIndex("RoleId");

                    b.ToTable("Approvals");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.ApprovalLevel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("LevelName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("ApprovalLevels");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.ApprovalPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<int>("EscalationHours")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("RiskLevel")
                        .HasColumnType("integer");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<int>("SequenceOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("RoleId");

                    b.ToTable("ApprovalPolicies");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.AssetAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AssignedToId")
                        .HasColumnType("uuid");

                    b.Property<string>("ConditionOnReturn")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("InventoryItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ReturnedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToId");

                    b.HasIndex("InventoryItemId");

                    b.ToTable("AssetAssignments");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("PerformedById")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PerformedById");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("HeadId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("HeadId");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.Inventory.GoodsReceipt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("InventoryProcessingError")
                        .HasColumnType("text");

                    b.Property<string>("InventoryProcessingStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("PurchaseOrderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReceivedById")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ReceivedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseOrderId");

                    b.HasIndex("ReceivedById");

                    b.ToTable("GoodsReceipts");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.Inventory.GoodsReceiptItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("GoodsReceiptId")
                        .HasColumnType("uuid");

                    b.Property<bool>("InventoryInserted")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("InventoryInsertedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("InventoryItemId")
                        .HasColumnType("uuid");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<Guid>("PurchaseOrderItemId")
                        .HasColumnType("uuid");

                    b.Property<int>("QuantityReceived")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GoodsReceiptId");

                    b.HasIndex("InventoryItemId");

                    b.HasIndex("PurchaseOrderItemId");

                    b.ToTable("GoodsReceiptItems");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.Inventory.InventoryAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InventoryItemId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsReturned")
                        .HasColumnType("boolean");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("ReferenceId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("InventoryItemId");

                    b.ToTable("InventoryAssignments");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.Inventory.InventoryCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CategoryCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("ParentCategoryId")
                        .HasColumnType("uuid");

                    b.Property<int>("RiskWeight")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CategoryCode")
                        .IsUnique();

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("InventoryCategories");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.Inventory.InventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("AssignedToId")
                        .HasColumnType("uuid");

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedById")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("InventoryCategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToId");

                    b.HasIndex("CreatedById");

                    b.HasIndex("InventoryCategoryId");

                    b.HasIndex("SKU")
                        .IsUnique();

                    b.ToTable("InventoryItems");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.Inventory.Stock", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AvailableQuantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("InventoryItemId")
                        .HasColumnType("uuid");

                    b.Property<int>("ReservedQuantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("InventoryItemId");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.Inventory.StockTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InventoryItemId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("StockTransactions");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.InventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssetTag")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("InventoryItem");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Group")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Permissions");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            Description = "View all users",
                            Group = "User",
                            Key = "VIEW_USERS"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            Description = "Add new users",
                            Group = "User",
                            Key = "CREATE_USER"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            Description = "Edit existing users",
                            Group = "User",
                            Key = "EDIT_USER"
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            Description = "Delete users",
                            Group = "User",
                            Key = "DELETE_USER"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000001"),
                            Description = "View roles",
                            Group = "Role",
                            Key = "VIEW_ROLES"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000002"),
                            Description = "Create new roles",
                            Group = "Role",
                            Key = "CREATE_ROLE"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000003"),
                            Description = "Edit roles",
                            Group = "Role",
                            Key = "EDIT_ROLE"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000004"),
                            Description = "Delete roles",
                            Group = "Role",
                            Key = "DELETE_ROLE"
                        },
                        new
                        {
                            Id = new Guid("20000000-0000-0000-0000-000000000005"),
                            Description = "Assign or revoke permissions for roles",
                            Group = "Role",
                            Key = "MANAGE_ROLE_PERMISSIONS"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000001"),
                            Description = "View departments",
                            Group = "Department",
                            Key = "VIEW_DEPARTMENTS"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000002"),
                            Description = "Add new departments",
                            Group = "Department",
                            Key = "CREATE_DEPARTMENT"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000003"),
                            Description = "Edit departments",
                            Group = "Department",
                            Key = "EDIT_DEPARTMENT"
                        },
                        new
                        {
                            Id = new Guid("30000000-0000-0000-0000-000000000004"),
                            Description = "Delete departments",
                            Group = "Department",
                            Key = "DELETE_DEPARTMENT"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000001"),
                            Description = "Create a new vendor",
                            Group = "Vendor",
                            Key = "ADD_VENDOR"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000002"),
                            Description = "Edit vendor details",
                            Group = "Vendor",
                            Key = "EDIT_VENDOR"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000003"),
                            Description = "View vendor records",
                            Group = "Vendor",
                            Key = "VIEW_VENDOR"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000004"),
                            Description = "Approve or reject vendor applications",
                            Group = "Vendor",
                            Key = "APPROVE_VENDOR"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000005"),
                            Description = "Delete vendor records",
                            Group = "Vendor",
                            Key = "DELETE_VENDOR"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000006"),
                            Description = "Upload vendor documents",
                            Group = "Vendor",
                            Key = "UPLOAD_VENDOR_DOCUMENT"
                        },
                        new
                        {
                            Id = new Guid("40000000-0000-0000-0000-000000000007"),
                            Description = "Delete vendor document",
                            Group = "Vendor",
                            Key = "DELETE_VENDOR_DOCUMENT"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000001"),
                            Description = "Create purchase requisition",
                            Group = "Procurement",
                            Key = "CREATE_REQUISITION"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000002"),
                            Description = "Approve requisition",
                            Group = "Procurement",
                            Key = "APPROVE_REQUISITION"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000003"),
                            Description = "Create purchase order",
                            Group = "Procurement",
                            Key = "CREATE_PURCHASE_ORDER"
                        },
                        new
                        {
                            Id = new Guid("50000000-0000-0000-0000-000000000004"),
                            Description = "View purchase order details",
                            Group = "Procurement",
                            Key = "VIEW_PURCHASE_ORDER"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000001"),
                            Description = "View inventory list",
                            Group = "Inventory",
                            Key = "VIEW_INVENTORY"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000002"),
                            Description = "Add new inventory items",
                            Group = "Inventory",
                            Key = "ADD_INVENTORY_ITEM"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000003"),
                            Description = "Update inventory items",
                            Group = "Inventory",
                            Key = "UPDATE_INVENTORY_ITEM"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000004"),
                            Description = "Delete inventory items",
                            Group = "Inventory",
                            Key = "DELETE_INVENTORY_ITEM"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000005"),
                            Description = "Assign asset to employee",
                            Group = "Inventory",
                            Key = "ASSIGN_ASSET"
                        },
                        new
                        {
                            Id = new Guid("60000000-0000-0000-0000-000000000006"),
                            Description = "Return assigned asset",
                            Group = "Inventory",
                            Key = "RETURN_ASSET"
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000001"),
                            Description = "View reports",
                            Group = "Reporting",
                            Key = "VIEW_REPORTS"
                        },
                        new
                        {
                            Id = new Guid("70000000-0000-0000-0000-000000000002"),
                            Description = "Export reports to PDF/Excel",
                            Group = "Reporting",
                            Key = "EXPORT_REPORTS"
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000001"),
                            Description = "Change global settings",
                            Group = "System",
                            Key = "MANAGE_SYSTEM_SETTINGS"
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000002"),
                            Description = "View audit logs",
                            Group = "System",
                            Key = "VIEW_AUDIT_LOGS"
                        },
                        new
                        {
                            Id = new Guid("80000000-0000-0000-0000-000000000003"),
                            Description = "Configure approval workflow",
                            Group = "System",
                            Key = "MANAGE_APPROVAL_WORKFLOW"
                        },
                        new
                        {
                            Id = new Guid("90000000-0000-0000-0000-000000000001"),
                            Description = "View category",
                            Group = "Category",
                            Key = "VIEW_CATEGORIES"
                        },
                        new
                        {
                            Id = new Guid("11000000-0000-0000-0000-000000000001"),
                            Description = "View permissions",
                            Group = "Permissions",
                            Key = "VIEW_PERMISSIONS"
                        });
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.PurchaseOrder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DeliveryStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PurchaseOrderNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("QuotationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequisitionId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<decimal>("SubTotal")
                        .HasColumnType("numeric");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Vat")
                        .HasColumnType("numeric");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QuotationId");

                    b.HasIndex("RequisitionId");

                    b.HasIndex("VendorId");

                    b.ToTable("PurchaseOrders");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.PurchaseOrderItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("numeric");

                    b.Property<Guid>("PurchaseOrderId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("TaxPercentage")
                        .HasColumnType("numeric");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseOrderId");

                    b.ToTable("PurchaseOrderItems");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.RequestForQuotations.Quotation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DeliveryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("boolean");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RfqId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RfqVendorId")
                        .HasColumnType("uuid");

                    b.Property<string>("SignedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SubmissionMethod")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("RfqId");

                    b.HasIndex("RfqVendorId");

                    b.ToTable("Quotations");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.RequestForQuotations.QuotationItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("DeliveryDays")
                        .HasColumnType("integer");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("QuotationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Remarks")
                        .HasColumnType("text");

                    b.Property<decimal>("TaxPercentage")
                        .HasColumnType("numeric");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("QuotationId");

                    b.ToTable("QuotationItems");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.RequestForQuotations.RequestForQuotation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RequisitionId")
                        .HasColumnType("uuid");

                    b.Property<string>("RfqNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SubmissionDeadline")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("RequisitionId");

                    b.ToTable("RequestForQuotations");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.RequestForQuotations.RfqAccessToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EmailSent")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsExpired")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("boolean");

                    b.Property<Guid>("RfqId")
                        .HasColumnType("uuid");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RfqId");

                    b.HasIndex("VendorId");

                    b.ToTable("RfqAccessTokens");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.RequestForQuotations.RfqAudit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PerformedBy")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RfqId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RfqId");

                    b.ToTable("RfqAudits");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.RequestForQuotations.RfqVendor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("RfqId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("TokenExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ViewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AccessToken")
                        .IsUnique();

                    b.HasIndex("RfqId");

                    b.HasIndex("VendorId");

                    b.ToTable("RfqVendors");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.Requisition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsUrgent")
                        .HasColumnType("boolean");

                    b.Property<Guid>("RequestedById")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RequestedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequisitionNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("RiskScore")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("RequestedById");

                    b.HasIndex("RequisitionNumber")
                        .IsUnique();

                    b.ToTable("Requisitions");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.RequisitionItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("EstimatedCost")
                        .HasColumnType("numeric");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<Guid>("RequisitionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RequisitionId");

                    b.ToTable("RequisitionItems");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c76abcb8-63b5-4e14-8428-3a9a9b7ad001"),
                            Description = "",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = new Guid("d27f6b43-9f64-4b13-a289-fd7744f2f102"),
                            Description = "",
                            Name = "CEO"
                        },
                        new
                        {
                            Id = new Guid("b38b2e23-6a7e-4c6d-9d5e-437a78c7b203"),
                            Description = "",
                            Name = "ProcurementOfficer"
                        });
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.RolePermission", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");

                    b.HasData(
                        new
                        {
                            RoleId = new Guid("c76abcb8-63b5-4e14-8428-3a9a9b7ad001"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("c76abcb8-63b5-4e14-8428-3a9a9b7ad001"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            RoleId = new Guid("c76abcb8-63b5-4e14-8428-3a9a9b7ad001"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            RoleId = new Guid("c76abcb8-63b5-4e14-8428-3a9a9b7ad001"),
                            PermissionId = new Guid("10000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            RoleId = new Guid("c76abcb8-63b5-4e14-8428-3a9a9b7ad001"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("c76abcb8-63b5-4e14-8428-3a9a9b7ad001"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            RoleId = new Guid("c76abcb8-63b5-4e14-8428-3a9a9b7ad001"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            RoleId = new Guid("c76abcb8-63b5-4e14-8428-3a9a9b7ad001"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            RoleId = new Guid("c76abcb8-63b5-4e14-8428-3a9a9b7ad001"),
                            PermissionId = new Guid("20000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            RoleId = new Guid("c76abcb8-63b5-4e14-8428-3a9a9b7ad001"),
                            PermissionId = new Guid("30000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("c76abcb8-63b5-4e14-8428-3a9a9b7ad001"),
                            PermissionId = new Guid("30000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            RoleId = new Guid("c76abcb8-63b5-4e14-8428-3a9a9b7ad001"),
                            PermissionId = new Guid("30000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            RoleId = new Guid("c76abcb8-63b5-4e14-8428-3a9a9b7ad001"),
                            PermissionId = new Guid("30000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            RoleId = new Guid("c76abcb8-63b5-4e14-8428-3a9a9b7ad001"),
                            PermissionId = new Guid("40000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("c76abcb8-63b5-4e14-8428-3a9a9b7ad001"),
                            PermissionId = new Guid("40000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            RoleId = new Guid("c76abcb8-63b5-4e14-8428-3a9a9b7ad001"),
                            PermissionId = new Guid("40000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            RoleId = new Guid("c76abcb8-63b5-4e14-8428-3a9a9b7ad001"),
                            PermissionId = new Guid("40000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            RoleId = new Guid("c76abcb8-63b5-4e14-8428-3a9a9b7ad001"),
                            PermissionId = new Guid("40000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            RoleId = new Guid("c76abcb8-63b5-4e14-8428-3a9a9b7ad001"),
                            PermissionId = new Guid("40000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            RoleId = new Guid("c76abcb8-63b5-4e14-8428-3a9a9b7ad001"),
                            PermissionId = new Guid("40000000-0000-0000-0000-000000000007")
                        },
                        new
                        {
                            RoleId = new Guid("c76abcb8-63b5-4e14-8428-3a9a9b7ad001"),
                            PermissionId = new Guid("50000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("c76abcb8-63b5-4e14-8428-3a9a9b7ad001"),
                            PermissionId = new Guid("50000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            RoleId = new Guid("c76abcb8-63b5-4e14-8428-3a9a9b7ad001"),
                            PermissionId = new Guid("50000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            RoleId = new Guid("c76abcb8-63b5-4e14-8428-3a9a9b7ad001"),
                            PermissionId = new Guid("50000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            RoleId = new Guid("c76abcb8-63b5-4e14-8428-3a9a9b7ad001"),
                            PermissionId = new Guid("60000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("c76abcb8-63b5-4e14-8428-3a9a9b7ad001"),
                            PermissionId = new Guid("60000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            RoleId = new Guid("c76abcb8-63b5-4e14-8428-3a9a9b7ad001"),
                            PermissionId = new Guid("60000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            RoleId = new Guid("c76abcb8-63b5-4e14-8428-3a9a9b7ad001"),
                            PermissionId = new Guid("60000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            RoleId = new Guid("c76abcb8-63b5-4e14-8428-3a9a9b7ad001"),
                            PermissionId = new Guid("60000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            RoleId = new Guid("c76abcb8-63b5-4e14-8428-3a9a9b7ad001"),
                            PermissionId = new Guid("60000000-0000-0000-0000-000000000006")
                        },
                        new
                        {
                            RoleId = new Guid("c76abcb8-63b5-4e14-8428-3a9a9b7ad001"),
                            PermissionId = new Guid("70000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("c76abcb8-63b5-4e14-8428-3a9a9b7ad001"),
                            PermissionId = new Guid("70000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            RoleId = new Guid("c76abcb8-63b5-4e14-8428-3a9a9b7ad001"),
                            PermissionId = new Guid("80000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("c76abcb8-63b5-4e14-8428-3a9a9b7ad001"),
                            PermissionId = new Guid("80000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            RoleId = new Guid("c76abcb8-63b5-4e14-8428-3a9a9b7ad001"),
                            PermissionId = new Guid("80000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            RoleId = new Guid("c76abcb8-63b5-4e14-8428-3a9a9b7ad001"),
                            PermissionId = new Guid("90000000-0000-0000-0000-000000000001")
                        },
                        new
                        {
                            RoleId = new Guid("c76abcb8-63b5-4e14-8428-3a9a9b7ad001"),
                            PermissionId = new Guid("11000000-0000-0000-0000-000000000001")
                        });
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.TotalAmountRiskScore", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MaxAmount")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MinAmount")
                        .HasColumnType("numeric");

                    b.Property<int>("RiskPoints")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("TotalAmountRiskScores");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("PasswordResetToken")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("PasswordResetTokenExpiration")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("PasswordResetTokenUsed")
                        .HasColumnType("boolean");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("ProfileImagePublicId")
                        .HasColumnType("text");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a87f3d2b-0f0d-4b4e-9d2a-4e09d68f4104"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@nexusprocure.com",
                            FullName = "",
                            IsActive = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEHsHTY55ymmyC5FW7c6RpK2s/HWufLsNpUswO1iSjCFPadhi/WF+HZo86Twk4Rl4NQ==",
                            PasswordResetTokenExpiration = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordResetTokenUsed = false,
                            RoleId = new Guid("c76abcb8-63b5-4e14-8428-3a9a9b7ad001"),
                            Username = "admin"
                        },
                        new
                        {
                            Id = new Guid("a87f3d2b-0f0d-4b4e-9d2a-4e09d68f4103"),
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@mail.com",
                            FullName = "",
                            IsActive = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEHsHTY55ymmyC5FW7c6RpK2s/HWufLsNpUswO1iSjCFPadhi/WF+HZo86Twk4Rl4NQ==",
                            PasswordResetTokenExpiration = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PasswordResetTokenUsed = false,
                            RoleId = new Guid("c76abcb8-63b5-4e14-8428-3a9a9b7ad001"),
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.Vendor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("BankAccount")
                        .HasColumnType("text");

                    b.Property<string>("BankBranch")
                        .HasColumnType("text");

                    b.Property<string>("BankName")
                        .HasColumnType("text");

                    b.Property<string>("CompanyName")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<Guid?>("InventoryCategoryId")
                        .HasColumnType("uuid");

                    b.Property<string>("PaymentTerms")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TaxId")
                        .HasColumnType("text");

                    b.Property<string>("TaxType")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VendorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("InventoryCategoryId");

                    b.ToTable("Vendors");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.VendorCategory", b =>
                {
                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.HasKey("VendorId", "CategoryId");

                    b.HasIndex("CategoryId");

                    b.ToTable("VendorCategory");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.VendorDocument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FileName")
                        .HasColumnType("text");

                    b.Property<string>("FileType")
                        .HasColumnType("text");

                    b.Property<string>("FileUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PublicId")
                        .HasColumnType("text");

                    b.Property<Guid?>("UploadedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VendorId");

                    b.ToTable("VendorDocuments");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.Approval", b =>
                {
                    b.HasOne("NexusProcure.Core.Entities.User", "ApprovedBy")
                        .WithMany()
                        .HasForeignKey("ApprovedById");

                    b.HasOne("NexusProcure.Core.Entities.Requisition", null)
                        .WithMany("Approvals")
                        .HasForeignKey("RequisitionId");

                    b.HasOne("NexusProcure.Core.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApprovedBy");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.ApprovalLevel", b =>
                {
                    b.HasOne("NexusProcure.Core.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.ApprovalPolicy", b =>
                {
                    b.HasOne("NexusProcure.Core.Entities.Inventory.InventoryCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexusProcure.Core.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.AssetAssignment", b =>
                {
                    b.HasOne("NexusProcure.Core.Entities.User", "AssignedTo")
                        .WithMany("AssetAssignments")
                        .HasForeignKey("AssignedToId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexusProcure.Core.Entities.InventoryItem", "InventoryItem")
                        .WithMany("AssetAssignments")
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedTo");

                    b.Navigation("InventoryItem");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.AuditLog", b =>
                {
                    b.HasOne("NexusProcure.Core.Entities.User", "PerformedBy")
                        .WithMany()
                        .HasForeignKey("PerformedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PerformedBy");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.Department", b =>
                {
                    b.HasOne("NexusProcure.Core.Entities.User", "Head")
                        .WithMany()
                        .HasForeignKey("HeadId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Head");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.Inventory.GoodsReceipt", b =>
                {
                    b.HasOne("NexusProcure.Core.Entities.PurchaseOrder", "PurchaseOrder")
                        .WithMany()
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NexusProcure.Core.Entities.User", "ReceivedBy")
                        .WithMany()
                        .HasForeignKey("ReceivedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PurchaseOrder");

                    b.Navigation("ReceivedBy");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.Inventory.GoodsReceiptItem", b =>
                {
                    b.HasOne("NexusProcure.Core.Entities.Inventory.GoodsReceipt", "GoodsReceipt")
                        .WithMany("Items")
                        .HasForeignKey("GoodsReceiptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexusProcure.Core.Entities.Inventory.InventoryItem", "InventoryItem")
                        .WithMany()
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NexusProcure.Core.Entities.PurchaseOrderItem", "PurchaseOrderItem")
                        .WithMany()
                        .HasForeignKey("PurchaseOrderItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GoodsReceipt");

                    b.Navigation("InventoryItem");

                    b.Navigation("PurchaseOrderItem");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.Inventory.InventoryAssignment", b =>
                {
                    b.HasOne("NexusProcure.Core.Entities.Inventory.InventoryItem", "InventoryItem")
                        .WithMany()
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryItem");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.Inventory.InventoryCategory", b =>
                {
                    b.HasOne("NexusProcure.Core.Entities.Inventory.InventoryCategory", "ParentInventoryCategory")
                        .WithMany("SubCategories")
                        .HasForeignKey("ParentCategoryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ParentInventoryCategory");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.Inventory.InventoryItem", b =>
                {
                    b.HasOne("NexusProcure.Core.Entities.User", "AssignedTo")
                        .WithMany()
                        .HasForeignKey("AssignedToId");

                    b.HasOne("NexusProcure.Core.Entities.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById");

                    b.HasOne("NexusProcure.Core.Entities.Inventory.InventoryCategory", "InventoryCategory")
                        .WithMany("Items")
                        .HasForeignKey("InventoryCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedTo");

                    b.Navigation("CreatedBy");

                    b.Navigation("InventoryCategory");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.Inventory.Stock", b =>
                {
                    b.HasOne("NexusProcure.Core.Entities.Inventory.InventoryItem", "InventoryItem")
                        .WithMany()
                        .HasForeignKey("InventoryItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("InventoryItem");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.PurchaseOrder", b =>
                {
                    b.HasOne("NexusProcure.Core.Entities.RequestForQuotations.Quotation", "Quotation")
                        .WithMany()
                        .HasForeignKey("QuotationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexusProcure.Core.Entities.Requisition", "Requisition")
                        .WithMany("PurchaseOrders")
                        .HasForeignKey("RequisitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexusProcure.Core.Entities.Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quotation");

                    b.Navigation("Requisition");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.PurchaseOrderItem", b =>
                {
                    b.HasOne("NexusProcure.Core.Entities.PurchaseOrder", "PurchaseOrder")
                        .WithMany("Items")
                        .HasForeignKey("PurchaseOrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PurchaseOrder");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.RequestForQuotations.Quotation", b =>
                {
                    b.HasOne("NexusProcure.Core.Entities.RequestForQuotations.RequestForQuotation", "RequestForQuotation")
                        .WithMany("Quotations")
                        .HasForeignKey("RfqId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("NexusProcure.Core.Entities.RequestForQuotations.RfqVendor", "RfqVendor")
                        .WithMany()
                        .HasForeignKey("RfqVendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RequestForQuotation");

                    b.Navigation("RfqVendor");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.RequestForQuotations.QuotationItem", b =>
                {
                    b.HasOne("NexusProcure.Core.Entities.RequestForQuotations.Quotation", "Quotation")
                        .WithMany("Items")
                        .HasForeignKey("QuotationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quotation");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.RequestForQuotations.RequestForQuotation", b =>
                {
                    b.HasOne("NexusProcure.Core.Entities.Requisition", "Requisition")
                        .WithMany()
                        .HasForeignKey("RequisitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Requisition");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.RequestForQuotations.RfqAccessToken", b =>
                {
                    b.HasOne("NexusProcure.Core.Entities.RequestForQuotations.RequestForQuotation", "Rfq")
                        .WithMany()
                        .HasForeignKey("RfqId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexusProcure.Core.Entities.Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rfq");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.RequestForQuotations.RfqAudit", b =>
                {
                    b.HasOne("NexusProcure.Core.Entities.RequestForQuotations.RequestForQuotation", "Rfq")
                        .WithMany()
                        .HasForeignKey("RfqId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rfq");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.RequestForQuotations.RfqVendor", b =>
                {
                    b.HasOne("NexusProcure.Core.Entities.RequestForQuotations.RequestForQuotation", "Rfq")
                        .WithMany("Vendors")
                        .HasForeignKey("RfqId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexusProcure.Core.Entities.Vendor", "Vendor")
                        .WithMany()
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rfq");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.Requisition", b =>
                {
                    b.HasOne("NexusProcure.Core.Entities.Inventory.InventoryCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexusProcure.Core.Entities.Department", null)
                        .WithMany("Requisitions")
                        .HasForeignKey("DepartmentId");

                    b.HasOne("NexusProcure.Core.Entities.User", "RequestedBy")
                        .WithMany("Requisitions")
                        .HasForeignKey("RequestedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("RequestedBy");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.RequisitionItem", b =>
                {
                    b.HasOne("NexusProcure.Core.Entities.Requisition", "Requisition")
                        .WithMany("Items")
                        .HasForeignKey("RequisitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Requisition");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.RolePermission", b =>
                {
                    b.HasOne("NexusProcure.Core.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexusProcure.Core.Entities.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.User", b =>
                {
                    b.HasOne("NexusProcure.Core.Entities.Department", "Department")
                        .WithMany("Users")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("NexusProcure.Core.Entities.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.Vendor", b =>
                {
                    b.HasOne("NexusProcure.Core.Entities.Inventory.InventoryCategory", null)
                        .WithMany("Vendors")
                        .HasForeignKey("InventoryCategoryId");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.VendorCategory", b =>
                {
                    b.HasOne("NexusProcure.Core.Entities.Inventory.InventoryCategory", "Category")
                        .WithMany("VendorCategories")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NexusProcure.Core.Entities.Vendor", "Vendor")
                        .WithMany("VendorCategories")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.VendorDocument", b =>
                {
                    b.HasOne("NexusProcure.Core.Entities.Vendor", "Vendor")
                        .WithMany("Documents")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.Department", b =>
                {
                    b.Navigation("Requisitions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.Inventory.GoodsReceipt", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.Inventory.InventoryCategory", b =>
                {
                    b.Navigation("Items");

                    b.Navigation("SubCategories");

                    b.Navigation("VendorCategories");

                    b.Navigation("Vendors");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.InventoryItem", b =>
                {
                    b.Navigation("AssetAssignments");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.PurchaseOrder", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.RequestForQuotations.Quotation", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.RequestForQuotations.RequestForQuotation", b =>
                {
                    b.Navigation("Quotations");

                    b.Navigation("Vendors");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.Requisition", b =>
                {
                    b.Navigation("Approvals");

                    b.Navigation("Items");

                    b.Navigation("PurchaseOrders");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.User", b =>
                {
                    b.Navigation("AssetAssignments");

                    b.Navigation("Requisitions");
                });

            modelBuilder.Entity("NexusProcure.Core.Entities.Vendor", b =>
                {
                    b.Navigation("Documents");

                    b.Navigation("VendorCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
