using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace NexusProcure.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class ProcurementRequestUpdate : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_ProcurementRequests_Departments_DepartmentId",
                table: "ProcurementRequests");

            migrationBuilder.DropForeignKey(
                name: "FK_ProcurementRequests_Users_RequestedById",
                table: "ProcurementRequests");

            migrationBuilder.DropColumn(
                name: "IsAutoGenerated",
                table: "ProcurementRequests");

            migrationBuilder.DropColumn(
                name: "Purpose",
                table: "ProcurementRequests");

            migrationBuilder.DropColumn(
                name: "SourceInventoryRequestId",
                table: "ProcurementRequests");

            migrationBuilder.RenameColumn(
                name: "RequestedById",
                table: "ProcurementRequests",
                newName: "RequestedByUserId");

            migrationBuilder.RenameColumn(
                name: "DepartmentId",
                table: "ProcurementRequests",
                newName: "InventoryRequestId");

            migrationBuilder.RenameIndex(
                name: "IX_ProcurementRequests_RequestedById",
                table: "ProcurementRequests",
                newName: "IX_ProcurementRequests_RequestedByUserId");

            migrationBuilder.RenameIndex(
                name: "IX_ProcurementRequests_DepartmentId",
                table: "ProcurementRequests",
                newName: "IX_ProcurementRequests_InventoryRequestId");

            migrationBuilder.RenameColumn(
                name: "Quantity",
                table: "ProcurementRequestItems",
                newName: "RequiredProcurementQuantity");

            migrationBuilder.RenameColumn(
                name: "ItemId",
                table: "ProcurementRequestItems",
                newName: "InventoryStockId");

            migrationBuilder.AlterColumn<string>(
                name: "Status",
                table: "ProcurementRequests",
                type: "character varying(50)",
                maxLength: 50,
                nullable: false,
                oldClrType: typeof(int),
                oldType: "integer");

            migrationBuilder.AddColumn<DateTime>(
                name: "ApprovedAt",
                table: "ProcurementRequests",
                type: "timestamp with time zone",
                nullable: false,
                defaultValue: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));

            migrationBuilder.AddColumn<Guid>(
                name: "ApprovedByManagerId",
                table: "ProcurementRequests",
                type: "uuid",
                nullable: false,
                defaultValue: new Guid("00000000-0000-0000-0000-000000000000"));

            migrationBuilder.AddColumn<string>(
                name: "ManagerRemarks",
                table: "ProcurementRequests",
                type: "character varying(1000)",
                maxLength: 1000,
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "AvailableQuantity",
                table: "ProcurementRequestItems",
                type: "integer",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<Guid>(
                name: "InventoryRequestItemId",
                table: "ProcurementRequestItems",
                type: "uuid",
                nullable: false,
                defaultValue: new Guid("00000000-0000-0000-0000-000000000000"));

            migrationBuilder.AddColumn<string>(
                name: "Notes",
                table: "ProcurementRequestItems",
                type: "character varying(500)",
                maxLength: 500,
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "RequestedQuantity",
                table: "ProcurementRequestItems",
                type: "integer",
                nullable: false,
                defaultValue: 0);

            migrationBuilder.AddColumn<DateTime>(
                name: "ExpectedDeliveryDate",
                table: "DeliveryDto",
                type: "timestamp with time zone",
                nullable: true);

            migrationBuilder.CreateIndex(
                name: "IX_ProcurementRequests_ApprovedByManagerId",
                table: "ProcurementRequests",
                column: "ApprovedByManagerId");

            migrationBuilder.CreateIndex(
                name: "IX_ProcurementRequestItems_InventoryRequestItemId",
                table: "ProcurementRequestItems",
                column: "InventoryRequestItemId");

            migrationBuilder.CreateIndex(
                name: "IX_ProcurementRequestItems_InventoryStockId",
                table: "ProcurementRequestItems",
                column: "InventoryStockId");

            migrationBuilder.AddForeignKey(
                name: "FK_ProcurementRequestItems_InventoryRequestItems_InventoryRequ~",
                table: "ProcurementRequestItems",
                column: "InventoryRequestItemId",
                principalTable: "InventoryRequestItems",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_ProcurementRequestItems_InventoryStocks_InventoryStockId",
                table: "ProcurementRequestItems",
                column: "InventoryStockId",
                principalTable: "InventoryStocks",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_ProcurementRequests_InventoryRequests_InventoryRequestId",
                table: "ProcurementRequests",
                column: "InventoryRequestId",
                principalTable: "InventoryRequests",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_ProcurementRequests_Users_ApprovedByManagerId",
                table: "ProcurementRequests",
                column: "ApprovedByManagerId",
                principalTable: "Users",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);

            migrationBuilder.AddForeignKey(
                name: "FK_ProcurementRequests_Users_RequestedByUserId",
                table: "ProcurementRequests",
                column: "RequestedByUserId",
                principalTable: "Users",
                principalColumn: "Id",
                onDelete: ReferentialAction.Restrict);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_ProcurementRequestItems_InventoryRequestItems_InventoryRequ~",
                table: "ProcurementRequestItems");

            migrationBuilder.DropForeignKey(
                name: "FK_ProcurementRequestItems_InventoryStocks_InventoryStockId",
                table: "ProcurementRequestItems");

            migrationBuilder.DropForeignKey(
                name: "FK_ProcurementRequests_InventoryRequests_InventoryRequestId",
                table: "ProcurementRequests");

            migrationBuilder.DropForeignKey(
                name: "FK_ProcurementRequests_Users_ApprovedByManagerId",
                table: "ProcurementRequests");

            migrationBuilder.DropForeignKey(
                name: "FK_ProcurementRequests_Users_RequestedByUserId",
                table: "ProcurementRequests");

            migrationBuilder.DropIndex(
                name: "IX_ProcurementRequests_ApprovedByManagerId",
                table: "ProcurementRequests");

            migrationBuilder.DropIndex(
                name: "IX_ProcurementRequestItems_InventoryRequestItemId",
                table: "ProcurementRequestItems");

            migrationBuilder.DropIndex(
                name: "IX_ProcurementRequestItems_InventoryStockId",
                table: "ProcurementRequestItems");

            migrationBuilder.DropColumn(
                name: "ApprovedAt",
                table: "ProcurementRequests");

            migrationBuilder.DropColumn(
                name: "ApprovedByManagerId",
                table: "ProcurementRequests");

            migrationBuilder.DropColumn(
                name: "ManagerRemarks",
                table: "ProcurementRequests");

            migrationBuilder.DropColumn(
                name: "AvailableQuantity",
                table: "ProcurementRequestItems");

            migrationBuilder.DropColumn(
                name: "InventoryRequestItemId",
                table: "ProcurementRequestItems");

            migrationBuilder.DropColumn(
                name: "Notes",
                table: "ProcurementRequestItems");

            migrationBuilder.DropColumn(
                name: "RequestedQuantity",
                table: "ProcurementRequestItems");

            migrationBuilder.DropColumn(
                name: "ExpectedDeliveryDate",
                table: "DeliveryDto");

            migrationBuilder.RenameColumn(
                name: "RequestedByUserId",
                table: "ProcurementRequests",
                newName: "RequestedById");

            migrationBuilder.RenameColumn(
                name: "InventoryRequestId",
                table: "ProcurementRequests",
                newName: "DepartmentId");

            migrationBuilder.RenameIndex(
                name: "IX_ProcurementRequests_RequestedByUserId",
                table: "ProcurementRequests",
                newName: "IX_ProcurementRequests_RequestedById");

            migrationBuilder.RenameIndex(
                name: "IX_ProcurementRequests_InventoryRequestId",
                table: "ProcurementRequests",
                newName: "IX_ProcurementRequests_DepartmentId");

            migrationBuilder.RenameColumn(
                name: "RequiredProcurementQuantity",
                table: "ProcurementRequestItems",
                newName: "Quantity");

            migrationBuilder.RenameColumn(
                name: "InventoryStockId",
                table: "ProcurementRequestItems",
                newName: "ItemId");

            migrationBuilder.AlterColumn<int>(
                name: "Status",
                table: "ProcurementRequests",
                type: "integer",
                nullable: false,
                oldClrType: typeof(string),
                oldType: "character varying(50)",
                oldMaxLength: 50);

            migrationBuilder.AddColumn<bool>(
                name: "IsAutoGenerated",
                table: "ProcurementRequests",
                type: "boolean",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<string>(
                name: "Purpose",
                table: "ProcurementRequests",
                type: "text",
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<Guid>(
                name: "SourceInventoryRequestId",
                table: "ProcurementRequests",
                type: "uuid",
                nullable: true);

            migrationBuilder.AddForeignKey(
                name: "FK_ProcurementRequests_Departments_DepartmentId",
                table: "ProcurementRequests",
                column: "DepartmentId",
                principalTable: "Departments",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);

            migrationBuilder.AddForeignKey(
                name: "FK_ProcurementRequests_Users_RequestedById",
                table: "ProcurementRequests",
                column: "RequestedById",
                principalTable: "Users",
                principalColumn: "Id",
                onDelete: ReferentialAction.Cascade);
        }
    }
}
