using System;
using System.Collections.Generic;
using NexusProcure.Core.Enums;

namespace NexusProcure.Core.Entities.Inventory;

public class ProcurementRequest : BaseEntity
{
    public Guid Id { get; set; }

    public Guid RequestedById { get; set; }
    public User RequestedBy { get; set; }

    public Guid DepartmentId { get; set; }
    public Department Department { get; set; }

    public string Purpose { get; set; }

    public ProcurementStatus Status { get; set; }

    public bool IsAutoGenerated { get; set; }
    public Guid? SourceInventoryRequestId { get; set; }

    public ICollection<ProcurementRequestItem> Items { get; set; } = new List<ProcurementRequestItem>();
}